/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyApp {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MySelect {
        "ListLabel": string;
        "defaultValue"?: string | string[];
        "disabled": boolean;
        "enableSearch": boolean;
        "enableSelectAll": boolean;
        "enableSelectedItems": boolean;
        "multiSelect": boolean;
        "options": { label: any; value: string }[];
        "placeholder": string;
        "selectedItemsLabel": string;
    }
}
export interface MySelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMySelectElement;
}
declare global {
    interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {
    }
    var HTMLMyAppElement: {
        prototype: HTMLMyAppElement;
        new (): HTMLMyAppElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMySelectElementEventMap {
        "valueChanged": string | string[];
    }
    interface HTMLMySelectElement extends Components.MySelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMySelectElementEventMap>(type: K, listener: (this: HTMLMySelectElement, ev: MySelectCustomEvent<HTMLMySelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMySelectElementEventMap>(type: K, listener: (this: HTMLMySelectElement, ev: MySelectCustomEvent<HTMLMySelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMySelectElement: {
        prototype: HTMLMySelectElement;
        new (): HTMLMySelectElement;
    };
    interface HTMLElementTagNameMap {
        "my-app": HTMLMyAppElement;
        "my-component": HTMLMyComponentElement;
        "my-select": HTMLMySelectElement;
    }
}
declare namespace LocalJSX {
    interface MyApp {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MySelect {
        "ListLabel"?: string;
        "defaultValue"?: string | string[];
        "disabled"?: boolean;
        "enableSearch"?: boolean;
        "enableSelectAll"?: boolean;
        "enableSelectedItems"?: boolean;
        "multiSelect"?: boolean;
        "onValueChanged"?: (event: MySelectCustomEvent<string | string[]>) => void;
        "options"?: { label: any; value: string }[];
        "placeholder"?: string;
        "selectedItemsLabel"?: string;
    }
    interface IntrinsicElements {
        "my-app": MyApp;
        "my-component": MyComponent;
        "my-select": MySelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-app": LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-select": LocalJSX.MySelect & JSXBase.HTMLAttributes<HTMLMySelectElement>;
        }
    }
}
